on:
  push:
    branches:
      - master

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get current date and time
        env:
          TZ: "Asia/Tokyo"
        id: date
        run: echo "CURRENT_DATETIME=$(date +'%Y/%m/%d/%H/%M')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.CURRENT_DATETIME }}
          release_name: ${{ env.CURRENT_DATETIME }}
          body: ${{ github.event.pull_request.body }}
          draft: true
          prerelease: false

